Closes #8
eHarmony/aloha pull request #123
Opened 2016-12-19 17:40 UTC by deaktator

Changing API to use auditors.  Model trait will be vastly simplified.  Something like:

```scala
trait Model[-A, +B] extends (A => B)  // Main model API: just a function
trait TypeCtor { type TC[+A] }
trait AuditedModel[T <: TypeCtor, N, -A, +B <: T#TC[N]] extends Model[A, B] {
  private[aloha] def typeConstructed: AuditedModel[T, N, A, T#TC[N]] =
    this.asInstanceOf[AuditedModel[T, N, A, T#TC[N]]]
}
```

Still working out the APIs, variance, etc.  The nice thing is that everything works nicely in Java:

```java
import com.eharmony.aloha.score.audit.OptionAuditor.OptionTC;

@SuppressWarnings("unchecked")
static <A> Manifest<A> manifest(final String strRep) {
  return (Manifest<A>) ManifestParser.parse(strRep).right().get();
}

// Easy to create Auditors from Java!
Manifest<Integer> refInfoInt = manifest(Integer.class.getCanonicalName());
OptionAuditor<Integer> intAud = new OptionAuditor<>(refInfoInt);

Manifest<Float> refInfoFloat = manifest(Float.class.getCanonicalName());
OptionAuditor<Float> floatAud = new OptionAuditor<>(refInfoFloat);

// Easy to directly instantiate models.  Last two type parameters are the Model 
// type parameters.
ConstantModel<OptionTC, Integer, Object, Option<Integer>> cModel =
    new ConstantModel<>(ModelId.empty(), 1, intAud);

// Last two type parameters are the Model type parameters.
HierarchicalConstantModel<OptionTC, Integer, Float, Object, Option<Float>> hcm =
    HierarchicalConstantModel.createFromJava(ModelId.empty(), 2f, floatAud, cModel);

// Seamless downcasting to the model interface.
Model<Object, Option<Float>> m = hcm;

// Easy to call prediction function:
Option<Float> result = m.apply(null);    // null OK b/c model just returns a constant.
```

and of course, Scala works nicely:

```scala
val cm = ConstantModel(ModelId(), 1, OptionAuditor[Int])
val hcm = HierarchicalConstantModel(ModelId(), 2f, OptionAuditor[Float])(cm)
val hcmModel: Model[Any, Option[Float]] = hcm
assert( Option(2f) == hcm( () ) )
```

2016-12-19 17:58 UTC, deaktator commented
Currently, [take3](https://github.com/eHarmony/aloha/tree/8-auditor/aloha-core/src/test/scala/com/eharmony/aloha/score/audit/take3) is the API I like the best.  I'd like to make this the de facto one.  It has lots of type parameters (some are redundant) but it works the best in Java and Scala.  It will work completely with type inference, even in Java.  For instance, even the `TypeCtor` interface is entirely for Java compatibility.  It could just be a higher kinded-type, but this doesn't work in Java.

2016-12-19 20:37 UTC, jmorra requested changes
This looks awesome.  I love the docs and the test.  But I can't help but to think I'm missing something.  Shouldn't there now be a new Model trait?  And the old Model trait should be removed?  Also this should become version 4.  It's a HUGE change.

2016-12-19 20:37 UTC, jmorra commented on aloha-core/src/main/scala/com/eharmony/aloha/score/audit/Auditor.scala
> +  * Created by deaktator on 12/9/16.
Can you add a description here about what an Auditor is.

2016-12-19 20:37 UTC, jmorra commented on aloha-core/src/main/scala/com/eharmony/aloha/score/audit/EitherAuditor.scala
> +//  override private[aloha] def failure[C](key: K, errorMsgs: => Seq[String], missingVarNames: => Set[String], childValues: Seq[Result]): Failure[K] = Failure(key, errorMsgs, missingVarNames, childVa
Remove dead code.

2016-12-19 20:57 UTC, deaktator commented
@jmorra The only thing to look at right now is the `take3` package in `src/test`.  This is self-contained and describes what the API will be.  The rest of the code is not yet done.  I just had to work through a bunch of different ways to accomplish the same thing and figure out what worked the best.  The `take3` one is very nice and doesn't required the specification of any types as evidenced by the first comment in the PR.  

The model factories will return a `Model[A, B]` which is really elegant.  It's just a Scala function and it will also have a `ModelIdentity`.

This took a long time to get right on the Java side.  I'll probably write up a blog article to describe the necessity of all of the components (especially the `TypeCtor1`).

Definitely agree on the version bump.  This is a definitely a major revision.

2016-12-19 21:27 UTC, jmorra commented on aloha-core/src/test/java/com/eharmony/aloha/score/audit/take3/JavaTestTake3.java
> +public class JavaTestTake3 {
This looks very nice.  Could you show an example instantiating from a JSON through the factory?

2016-12-19 21:36 UTC, deaktator commented on aloha-core/src/test/java/com/eharmony/aloha/score/audit/take3/JavaTestTake3.java
> +public class JavaTestTake3 {
I will.  That's not done yet.  I'm thinking something like: 

```java
OptionAuditor<Integer> aud = new OptionAuditor<>(refInfoInt);
Semantics<MyDataType> sem = ...;
ModelFactory<OptionTC, Integer, MyDataType, Option<Integer>> factory = 
    ModelFactory.createFromJava(..., sem, aud, ...);
File jsonFile = ...;

// Get model from factory.
Try<Model<MyDataType, Option<Integer>>> modelTry = factory.fromFile(jsonFile);
```

2017-01-31 21:01 UTC, deaktator commented
Just made a huge commit.  Everything is compiling at least.  Had to change every place where models and factories are defined, instantiated, and used.  Still trying to make the unit tests pass.

2017-01-31 21:03 UTC, deaktator commented
There still needs to be a fair amount of cleanup including looking at the documentation and modifying it.  I'm not going to try to rip out the protobuf stuff to a separate module in this PR.  That'll have to be a separate issue.

2017-02-02 21:16 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/Auditor.scala
> +trait Auditor[U, -N, +B <: U] {
Would it be possible to lengthen how the type parameters are named?  Scala does emphasize brevity, but I've always found it a little difficult to decipher what the type parameters are from first glance.

2017-02-06 22:27 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/scoreproto/ScoreAuditor.scala
> +          setModel(m)
Why is the model id and name only set in the error flow?  Does this pertain to the submodel identity during a recursive tree traversal?

2017-02-06 22:44 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/scoreproto/ScoreAuditor.scala
> +      b.setError(e).build
Is this Score proto eventually somehow propagated to the next auditor and becomes a part of the subValues argument?

2017-02-06 22:51 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/scoreproto/ScoreAuditor.scala
> +    ri match {
Like the factory method.

2017-02-06 23:07 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/scoreproto/ScoreAuditor.scala
> +      val v = value.getScore.getExtension(IntScore.impl)
protobufs have no support for bytes or shorts?

2017-02-06 23:21 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/scoreproto/ScoreAuditor.scala
> +sealed abstract class ScoreAuditor[N] extends MorphableAuditor[Score, N, Score]
I assume once we move away from protobufs, the Score protos will be replaced by some other type, and there would be some other ScoreAuditor type for non-protos.

Would it make sense to rename this to ScoreProtoAuditor instead?

2017-02-06 23:21 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/scoreproto/ScoreAuditor.scala
> +      val v = value.getScore.getExtension(IntScore.impl)
Looked at the docs, apparently not.

2017-02-06 23:23 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/algebra/NaturalOptionTransformation.scala
> +trait NaturalOptionTransformation[F[_], G[_]] {
If I understand this correctly, this is to convert one higher kinded type to an option of another higher kinded type.  Why is it needed?

2017-02-06 23:35 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/scoreproto/ScoreAuditor.scala
> +        else None
Do we want to log this or propogate this somehow?  It seems like a silent error.

2017-02-06 23:54 UTC, vsuthichai commented
The last commit has been **far** more legible to me, though it's still taking some effort to humanly ingest all the type parameters.  From what I understand while reading the code, the auditors' whole purpose is to recursively aggregate the scores and errors together to return to the caller.  

Does it make sense to lock down the Auditor trait's success and failure method signatures with those specific parameters:  `valueToAudit`, `missingVarNames`, etc.  It seems inflexible.  Would using some sort of context object that contains that information be better?

2017-02-07 00:08 UTC, vsuthichai commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/OptionAuditor.scala
> +case class OptionAuditor[A]() extends MorphableAuditor[Option[_], A, Option[A]] {
Not quite sure I understand what this is for.

2017-02-11 04:25 UTC, deaktator commented
***Everything is now compiling and all unit tests in all submodules are passing!***

Questions for @vsuthichai @jmorra:

1. Should we delete ensemble models package?  It's never been used and there has never been an ability to create via a model factory.
1. When should we move protos out of `aloha-core`? I want to do this ASAP, but this will affect things like ModelRunnerTool and dataset generation based on protocol buffers.  As a consequence, this will involve a substantial amount of refactoring command line tools.

2017-02-11 04:30 UTC, deaktator commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/OptionAuditor.scala
> +case class OptionAuditor[A]() extends MorphableAuditor[Option[_], A, Option[A]] {
I want to understand what you don't understand.  Can you elaborate?

2017-02-11 04:37 UTC, deaktator commented
@vsuthichai How would providing a context to the `Auditor` `success` and `failure` method allow it to be more expandable?  I like the idea but I'm not seeing how this would allow us to inject additional information without rewriting all of the model implementations.

2017-02-14 04:54 UTC, jon-morra-zefr approved these changes
I've left some comments, but obviously this is a lot.  Let me know if there is something specific that you want me to look at, otherwise this looks good.

2017-02-14 04:54 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/Auditor.scala
> +  def failure(modelId: ModelIdentity,
Why does an auditor need to know about the `ModelIdentity`?

2017-02-14 04:54 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/factory/ModelFactory.scala
> +//  * @param factory an untyped factory the produces models of kind M
grammar

2017-02-14 04:54 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/factory/ModelFactory.scala
> +  * @param semantics
These docs seem missing.

2017-02-14 04:54 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/factory/ModelFactory.scala
> +    * From old documentation in ModelFactory
Why do we care about old docs?

2017-02-14 04:54 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/factory/ModelFactory.scala
> +      jsonMaybe: Try[JsObject], // TODO: Should be a Try[JsObject]
It is

2017-02-21 20:49 UTC, jmorra commented
To your comment about removing code.  I think that's a good idea.  The direction of the project does not necessitate these models anymore.

I think we've moving the protos out in the next PR, right?

2017-02-21 20:49 UTC, jmorra approved these changes
Too much to review in detail, but I've looked at some of it and it looks good.

2017-02-23 21:40 UTC, vsuthichai approved these changes
Approved!

2017-02-23 21:48 UTC, vsuthichai approved these changes
Approved, take two!

2017-02-23 21:58 UTC, sahil-goyal approved these changes

2017-02-23 22:06 UTC, merged