Closes #155
eHarmony/aloha pull request #156
Opened 2017-05-06 00:36 UTC by deaktator

2017-05-06 00:42 UTC, deaktator reviewed
As always your coding is impeccable but your ideas are 'eh'. 😜

2017-05-06 00:42 UTC, deaktator commented on aloha-core/src/test/scala/com/eharmony/aloha/auditor/impl/TreeAuditorTest.scala
> +    assertEquals(Vector(Vector(1,2,3), Vector(1,2,4), Vector(1,5,6), Vector(1,5,7)), paths)
Is this enough to determine the ordering works?

2017-05-06 00:42 UTC, deaktator commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +      def dfs(st: List[Tree[Any]], done: List[Tree[Any]]): List[Tree[Any]] = {
@jmorra What do you think about the types here?

2017-05-06 00:42 UTC, deaktator commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +      def dfs(st: List[Vector[Tree[Any]]], done: Vector[Vector[Tree[Any]]]): Vector[Vector[Tree[Any]]] = {
@jmorra What do you think about the types here?

2017-05-06 00:42 UTC, deaktator commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +        st match {
***I love writing DFS in a function language!***

2017-05-06 00:42 UTC, deaktator commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +  private val accumErrs: (Seq[String], Seq[Tree[_]]) => sci.Seq[String] =
These are here to avoid creating the exact same function over and over again.

2017-05-06 00:42 UTC, deaktator commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +case class TreeAuditor[N](accumulateErrors: Boolean = false,
Add comments for these parameters.

2017-05-06 00:42 UTC, deaktator commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +  sealed trait Tree[+N] {
Do we want an upper type bound on the type that parametrizes `Tree`s?  Didn't do it here but might be useful.  The problem is that it makes creating TreeAuditors annoying like with other auditors.  I think the point here is to maintain the audit trail without too much typefu.

2017-05-08 17:01 UTC, jon-morra-zefr requested changes
Left a few comments to consider.

2017-05-08 17:01 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +case class TreeAuditor[N](accumulateErrors: Boolean = false,
Agreed

2017-05-08 17:01 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +  private val accumErrs: (Seq[String], Seq[Tree[_]]) => sci.Seq[String] =
Shouldn't these be lazy?

2017-05-08 17:01 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +  sealed trait Tree[+N] {
I agree, don't make using this annoying.

2017-05-08 17:01 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +      def dfs(st: List[Vector[Tree[Any]]], done: Vector[Vector[Tree[Any]]]): Vector[Vector[Tree[Any]]] = {
`Any` is scary.  Could we parametrize the type?

2017-05-08 17:01 UTC, jon-morra-zefr commented on aloha-core/src/main/scala/com/eharmony/aloha/audit/impl/TreeAuditor.scala
> +          case Nil => done.reverse
Why reverse?

2017-05-08 17:01 UTC, jon-morra-zefr commented on aloha-core/src/test/scala/com/eharmony/aloha/auditor/impl/TreeAuditorTest.scala
> +    assertEquals(Vector(Vector(1,2,3), Vector(1,2,4), Vector(1,5,6), Vector(1,5,7)), paths)
Yup

2017-05-08 17:01 UTC, jon-morra-zefr commented on aloha-core/src/test/scala/com/eharmony/aloha/auditor/impl/TreeAuditorTest.scala
> +}
newline

2017-05-09 21:37 UTC, jmorra approved these changes
Looks good

2017-05-09 22:11 UTC, ryan-deak-zefr commented
Merging.

2017-05-09 22:12 UTC, merged