Closes #164
eHarmony/aloha pull request #167
Opened 2017-08-18 23:56 UTC by deaktator

Updated VW version to 8.4.1.  

Only added support for 

- `VWScalarLearner`
- `VWProbLearner`
- `VWMulticlassLearner`

These are the types that extends `VWIntLearner` and `VWFloatLearner`.

2017-08-19 02:22 UTC, jon-morra-zefr requested changes
Very small change, but it looks good.

2017-08-19 02:22 UTC, jon-morra-zefr commented on aloha-vw-jni/src/main/scala/com/eharmony/aloha/models/vw/jni/VwJniModel.scala
> +      (i: Int) => tc(ls.values(i - 1))
Why are you subtracting 1 here?  Can you add a comment.

2017-08-21 16:13 UTC, jmorra commented
This looks great, but since we're updating dependent ML libraries, can we also move the H2O version to 3.10.3.2.  This is the version we're currently using.

2017-08-21 22:37 UTC, jmorra approved these changes
Looks great

2017-08-22 00:06 UTC, merged