Closes #203
eHarmony/aloha pull request #204
Opened 2017-11-28 23:25 UTC by deaktator

## Summary

There was some discussion as to whether feature function bodies are only called when data is present.  While this has always been the design, I don't think there are ever a test for this.  This was added to ***ensure*** that's the case. 

## Resolves
* Provides guarantees related to #203

## Tests
See `CompiledSemanticsTest.testFeatureFunctionsDoNotCallReferencedFunctionsWhenDataIsMissing` in *aloha-core*.  Also adds support for doing a similar thing with other `CompiledSemanticsPlugin`s by creating a trait that can be mixed into test class companion objects.

## Code Reviewer(s)
@jmorra

2017-11-29 00:23 UTC, deaktator commented on aloha-core/src/test/scala/com/eharmony/aloha/semantics/LazyInitSupport.scala
> +  private val indicator = new AtomicBoolean(NotCalled)
privacy is important here, since we don't want the sub type to modify these.

2017-11-29 00:23 UTC, deaktator commented on aloha-core/src/test/scala/com/eharmony/aloha/semantics/LazyInitSupport.scala
> +private[aloha] abstract class LazyInitSupport {
Making this an abstract class locks down the privacy of the members so they can't be accessed in sub-classes without trickery.

2017-11-29 00:23 UTC, deaktator commented on aloha-core/src/test/scala/com/eharmony/aloha/semantics/LazyInitSupport.scala
> +  private lazy val wasCalled = indicator.compareAndSet(NotCalled, Called)
This was added to check that lazy vals work. If lazy vals, didn't work, that would likely be a Scala language problem, but concerns were raised about this in conversations, so I felt it prudent to add.

2017-11-29 00:23 UTC, deaktator commented on aloha-core/src/test/scala/com/eharmony/aloha/semantics/compiled/plugin/AnyNameMissingValueSemanticsPlugin.scala
> +    evOpt: A <:< Option[_])
Ensures `A` is an `Option`.

2017-11-29 00:23 UTC, deaktator commented on aloha-core/src/test/scala/com/eharmony/aloha/semantics/compiled/plugin/AnyNameMissingValueSemanticsPlugin.scala
> +    Right(OptionalAccessorCode(Seq(s"(o: ${RefInfoOps.toString[A]}) => o.filterNot(_ => true)")))
Same as 

```scala
(o: Option[A]) => Option.empty[A]
```

2017-11-29 00:23 UTC, deaktator commented on aloha-core/src/test/scala/com/eharmony/aloha/semantics/compiled/CompiledSemanticsTest.scala
> +object CompiledSemanticsTest extends LazyInitSupport
Added the `code` function to the companion object so that it can be used in the spec in the test to determine if `code` is called.

2017-11-29 00:41 UTC, jmorra requested changes
We know that this isn't true, how does this reconcile that problem?

2018-04-03 17:49 UTC, deaktator commented
Closing.  This provides no real value.

2018-04-03 17:49 UTC, closed without merging